package com.nahunp.todoapp.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * The on-device cache — source of truth for what the UI reads (see
 * CLAUDE.md's "Offline support" section).
 *
 * `localKey` (Room-autogenerated) is what the domain/UI layer knows as
 * `TodoList.id` — stable for the row's entire local lifetime, independent
 * of sync state. Deliberately NOT the server's id: an earlier version of
 * this design tried reusing a temporary negative id as the Room primary
 * key and rewriting it in place once the real server id came back, which
 * broke any Flow-based observer already keyed on the old value (e.g. a
 * detail screen open on a list at the exact moment it finished syncing).
 * `serverId` (null until this list has been created on the backend) is
 * purely a sync-internal concern — SyncManager reads/writes it, nothing
 * above `data/local` ever sees it.
 */
@Entity(tableName = "todo_lists")
data class TodoListEntity(
    @PrimaryKey(autoGenerate = true) val localKey: Int = 0,
    val serverId: Int? = null,
    val name: String,
)
